general: 
  playwright: False
  delay: 2000 # Für playwright: Wartezeit, nach welcher kontrolliert wird, ob Website noch lädt
  pages_to_be_ignored: # Regex als Liste hinzufügen - URL wird ignoriert bei match
    
  


metadata: 
  date: 
    use_fallback_method: True # Falls kein Datum im HTML-head gefunden: Erstes Datum im Websitentext verwendet
    tag: 
    attrib: 
    name: 
    # Entweder nur tag angeben, oder alle 3 Elemente 
    # Beispiel: 
    # hmtl: <meta property="article:published_time" content="2024-04-02T16:09:32+00:00">
    # tag:meta, attrib:property, name:article:published_time -> content gets extracted
    # <published_date>05 juillet 2024</published_date>
    # tag:published_date

  title: 
    tag: 
    attrib: 
    name: 
    # Siehe date für Details

  author: 
    tag: 
    attrib: 
    name: 
    # Siehe date für Details


  volume: 
    extract_volume: True # Jedes volume aus Titel (nicht Text) extrahiert


text_extraction: 
  only_paragraphs: True # Text nur extrahiert aus <p>-tags (paragraphs) 
  specific_tags: # HTML-Elemente identifiziert über: tag, class oder id - nach jedem tag-class-id-Paar wird als fixe Kombination gesucht
    - tag: 
      class: 
      id: 
  # Weitere Paare können angegeben werden mit 
  # - tag: 
  #   class ..

    
  


output: 
  console: 
    verbose: True # Gibt während des crawlen zusätzliche Infos aus
    print_one_per: 1 # Gibt bei einer von n Websiten Infos aus

  file: # Welche Seiten sollen in Datei geschrieben werden - Alle Filteroptionen deaktivierbar mit -1
    percentage_limit: -1 # [1-100]: Jede Seite, auf der ein niedrigerer Prozentsatz an Text extrahiert wird, wird ignoriert
    word_count_limit: 150 # Gesamtzahl der Wörter pro Seite: Jede Seite mit weniger extrahierten Wörtern wird ignoriert
    mean_line_lenght_limit: -1 # Durchschnittliche Zahl an Wörtern pro (Text-)Zeile: Seite ignoriert, falls darunter
    
    doublons: # Duplikate entfernen 
      remove_doublons: True # Duplikatentfernung kann deaktiviert werden (vmtl. nie sinnvoll)
      threshold_value: 0.7 # Alle Seiten, die eine Übereinstimmung mit einer anderen Seite *über diesem Wert* haben, werden ignoriert. 