general: 
  delay: 0 # Wartezeit zwischen Aufrufen


metadata: 
  date: 
    use_fallback_method: True # Falls kein Datum im HTML-head gefunden: Erstes Datum im Websitentext verwendet
    tag: 
    attrib: 
    name: 
    # Entweder nur tag angeben, oder alle 3 Elemente 
    # Beispiel: 
    # hmtl: <meta property="article:published_time" content="2024-04-02T16:09:32+00:00">
    # tag:meta, attrib:property, name:article:published_time -> content gets extracted
    # <published_date>05 juillet 2024</published_date>
    # tag:published_date

  title: 
    tag: 
    attrib: 
    name: 
    # Siehe date für Details

  volume: 
    extract_volume: True # Jedes volume aus Titel (nicht Text) extrahiert


text_extraction: 
  only_paragraphs: True # Text nur extrahiert aus <p>-tags (paragraphs) 
  specific_tags: # HTML-Elemente identifiziert über: tag, class oder id. 
    tag: 
    class: 
    id: 
    # Mehrere Elemente können kombiniert werden, nach jedem wird unabhängig von den anderen gesucht


output: 
  console: 
    verbose: True # Gibt während des crawlen zusätzliche Infos aus
    print_one_per: 1 # Gibt bei einer von n Websiten Infos aus
  file: # Filteroptionen - deaktivieren mit -1
    percentage_limit: -1 # [1-100]: Jede Seite, auf der ein niedrigerer Prozentsatz an Text extrahiert wird, wird ignoriert
    word_count_limit: 150 # Gesamtzahl der Wörter pro Seite: Jede Seite mit weniger extrahierten Wörtern wird ignoriert
    mean_line_lenght_limit: 20 # Durchschnittliche Zahl an Wörtern pro (Text-)Zeile: Seite ignoriert, falls darunter