# ROBOTS.TXT
general: 
  ignore_robots.txt: True
  # If set to True, a wait period of 0.1 secs is used

# DATE
date: 
  use_fallback_method: True 
  # If set to True: If no date found in html head, date is taken from the first date in the website text. 
  deactivate_if_head: True
  # If set to True: When a date is found in a head, the fallback option is deactivated.

#VOLUME
volume: 
  extract_volume: True
  # If set to True: Any volume-like string is extracted from the title (but not the text)


#WEBSITE TEXT
text_extraction: 
  only_p_text: True
  # If set to True, only the text of the p (paragraph) tags is extracted
  specific_tags:
    id: Null
    class: Null
  # When modified, only text from those tags is extracted. This overwrites the 'only_p_text' option. 
  # Example: 
  # id: article iliade - for the following html: </div><div id="article-iliade" class="et_pb_module et_pb_text et_pb_text_2  et_pb_text_align_left et_pb_bg_layout_light"> [article]
  # class: article - for <article id="post-1882" class="post_item_single post_type_post post_format_ post-1882 post type-post s