#ROBOTS.TXT
ignore_robots.txt: True
#If set to True, a wait period of 0.1 secs is used
#WEBSITE TEXT
only_p_text: True
#If set to True, only the text of the p (paragraph) tags is extracted
specific_tags:
  - Null
#When modified, only text from those tags is extracted. This overwrites the 'only_p_text' option. 
#Currently untested, since I didn't find a page where this is actually working.
